name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # on button click

jobs:
  build:
    runs-on: macos-latest
    steps:
    -
        name: Set up Docker
        uses: crazy-max/ghaction-setup-docker@v1
    - run: |
        curl -s -L --output sysreptor.tar.gz https://github.com/syslifters/sysreptor/releases/latest/download/source-prebuilt.tar.gz
        tar -tzf sysreptor.tar.gz
        cd deploy
        cp app.env.example app.env
        ls -lah
        docker compose build app
    -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
    -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
    - name: Load .env file
      uses: xom9ikk/dotenv@v2
      with:
        path: deploy
        load-mode: strict
    -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: cocoa1344/sysreptor:latest , cocoa1344/sysreptor:${{ env.SYSREPTOR_VERSION }}
