- name: Docker Hub Description
    uses: peter-evans/dockerhub-description@v3
    with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        repository: Syslifters/sysreptor
